AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    allied.FtpToS3Lambda
    
    sync files on sftp to s3 bucket.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 400

Resources:

    FtpToS3Lambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: FtpToS3Lambda/build/
            Handler: app.lambda_handler
            Runtime: python3.6 
            AutoPublishAlias: live
            Policies:
                - AWSLambdaExecute
                - Statement:
                    - Action: [ 's3:*' ]
                      Effect: Allow
                      Resource: '*'
                    - Action: "ssm:GetParameters"
                      Effect: "Allow"
                      Resource: "*"
            Environment: 
                Variables:
                    BUCKET_DEST: allied-ftp-to-s3

    ScheduledRule: 
        Type: AWS::Events::Rule
        Properties: 
            Description: "ScheduledRule"
            ScheduleExpression: "rate(10 minutes)"
            State: "ENABLED"
            Targets: 
            - 
              Arn: 
                Fn::GetAtt: 
                    - "FtpToS3Lambda"
                    - "Arn"
              Id: "TargetFunctionV1"
    PermissionForEventsToInvokeLambda: 
        Type: AWS::Lambda::Permission
        Properties: 
            FunctionName: 
                Ref: "FtpToS3Lambda"
            Action: "lambda:InvokeFunction"
            Principal: "events.amazonaws.com"
            SourceArn: 
                Fn::GetAtt: 
                    - "ScheduledRule"
                    - "Arn"

Outputs:
    FtpToS3Lambda:
      Description: "sync files on sftp to s3 bucket."
      Value: !GetAtt FtpToS3Lambda.Arn

